
project_id = "fandkcurnirrnuecprtx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions]
[functions.get-user-profile]
verify_jwt = true
[functions.store-api-key]
verify_jwt = true
