-- Deprecated demo seed migration.
--
-- The original version inserted uuid_generate_v4() values into columns that
-- reference auth.users, so a fresh database reset failed with a foreign-key
-- violation. The following seed migration contains the anonymous, nullable
-- demo rows and is the only demo seed that should run on a fresh environment.
--
-- Existing deployed databases must not rewrite migration history; audit and
-- reconcile their data separately before applying the production schema.
