// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fandkcurnirrnuecprtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbmRrY3Vybmlycm51ZWNwcnR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDU5NjEsImV4cCI6MjA1OTAyMTk2MX0.KWiiQzMl0HHETRuLrzK6juh0HbdRaIj9Fl-tNbtW_Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);